core/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView
from . import views
from django.conf import settings   #para descargar archivos
from django.conf.urls.static import static  #para descargar archivos
from django.views.static import serve
from django.conf.urls.i18n import i18n_patterns
import os  #para el secret admin
import environ  #para el secret admin



urlpatterns = [
    path('i18n/', include("django.conf.urls.i18n")),
    # Paths del admin
    #path(os.environ.get('SECRET_ADMIN_URL') + '/admin/', admin.site.urls),
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name="home"),
    path('politica-cookies', views.cookie, name="politica-cookies"),
    path('formacion', include('formacion.urls',  namespace="formacion")),
    path('descargas', include('descargas.urls',  namespace="descargas")),
    path('quienes-somos', include('comitiva.urls',  namespace="comitiva")),
    path('contacto', include('contacto.urls',  namespace="contacto")),
 
]

    
#produccion
if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns #(No sure)
    #urlpatterns += staticfiles_urlpatterns() #(no sure)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)    

                                                                                                                                                                      

descargas/urls.py
from django.urls import path
#from .views import ReunionListView
from . import views
#from .views import HomeView



app_name = "descargas"

urlpatterns=[
   #path('', ReunionListView.as_view(), name='home')
    #path('', HomeView.as_view(), name="home"),
    path('reuniones', views.reunion, name='reuniones'),
    path('calendario', views.calendario, name='calendario'),
    path('permisos', views.permisos, name='permisos'),
    path('prevencion', views.prevencion, name='prevencion'),
    path('convenio', views.convenio, name='convenio'),
]

descargas/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class Reunion(models.Model):
    id = models.BigAutoField(
        primary_key=True,
    )

    title = models.CharField(
        max_length=150,
        verbose_name='Title'
    )


    description = models.TextField(
        max_length=500,
        verbose_name='Description',
         null=True,
        blank=True
    )
    
    published = models.DateTimeField(default=timezone.now)

    download = models.FileField(
        upload_to='reunion/'
    )





class Calendario(models.Model):
    id = models.BigAutoField(
        primary_key=True,
    )

    title = models.CharField(
        max_length=150,
        verbose_name='Title'
    )


    description = models.TextField(
        max_length=500,
        verbose_name='Description',
         null=True,
        blank=True
    )
    
    published = models.DateTimeField(default=timezone.now)

    download = models.FileField(
        upload_to='calendario/'
    )
    
    
    
    
    

class Permiso(models.Model):
    id = models.BigAutoField(
        primary_key=True,
    )

    title = models.CharField(
        max_length=150,
        verbose_name='Title'
    )


    description = models.TextField(
        max_length=500,
        verbose_name='Description',
         null=True,
        blank=True
    )
    
    published = models.DateTimeField(default=timezone.now)

    download = models.FileField(
        upload_to='permiso/'
    )
    
    
    
    
    

# Create your models here.

class Seguridad(models.Model):
    id = models.BigAutoField(
        primary_key=True,
    )

    title = models.CharField(
        max_length=150,
        verbose_name='Title'
    )


    description = models.TextField(
        max_length=500,
        verbose_name='Description',
         null=True,
        blank=True
    )
    
    published = models.DateTimeField(default=timezone.now)

    download = models.FileField(
        upload_to='seguridad/'
    )



# Create your models here.

class Convenio(models.Model):
    id = models.BigAutoField(
        primary_key=True,
    )

    title = models.CharField(
        max_length=150,
        verbose_name='Title'
    )


    description = models.TextField(
        max_length=500,
        verbose_name='Description',
         null=True,
        blank=True
    )
    
    published = models.DateTimeField(default=timezone.now)

    download = models.FileField(
        upload_to='convenio/', blank=True, null=True
    )

# Create your models here.

descargas/views.py
from django.http import FileResponse
from django.shortcuts import render
from django.views.generic import View
from .models import Reunion, Calendario, Permiso, Seguridad, Convenio



#class HomeView(View):
    #def get(self, request, *args, **kwargs):
        #context={
            
        #}
        #return render(request, 'index.html', context)                                                                          


def reunion(request):
    reuniones= Reunion.objects.all()
    context = {
        'reuniones': reuniones,
      }
 
    return render(request, 'descargas/reuniones.html', context)

def calendario(request):
    calendarios= Calendario.objects.all()
    context = {
        'calendarios': calendarios,
      }
 
    return render(request, 'descargas/calendarios.html', context)

def permisos(request):
    permisos= Permiso.objects.all()
    context = {
        'permisos': permisos,
      }
 
    return render(request, 'descargas/permisos.html', context)

def prevencion(request):
    prevenciones= Seguridad.objects.all()
    context = {
        'prevenciones': prevenciones,
      }
 
    return render(request, 'descargas/prevencion.html', context)

def convenio(request):
    convenios= Convenio.objects.all()
    context = {
        'convenios': convenios,
      }
 
    return render(request, 'descargas/convenio.html', context)
  
  

descargas/templates/cookies.html
{% extends 'base.html' %}
{% load static %}
{% block titulo %}Politica de Cookies{% endblock titulo %}
 
  <!-- --------------------------------------------------------------------->
   


      <!--------------------------------------------------------------------->
      <!--------------------------------------------------------------------->
      <div class="main">
        <!---------GRID COLUM 1/2-->
      <div class="main-primero"> 1</div>

      {% block content %}
        <!---GRID 2/10.COLUMN.........-->
        <div class="articulo"> 
<!--------------------------------------------------------------------->
   

       {% block cookie %}
       <div class="politica-cookie">
     <h1> Política de cookies</h1>
	<p> En cumplimiento con lo dispuesto en el artículo 22.2 de la Ley 34/2002, de 11 de julio, de 
	 Servicios de la Sociedad de la Información y de Comercio Electrónico, esta página web le informa, 
	 en esta sección, sobre la política de recogida y tratamiento de cookies.</p>
	 <p>
	 Según el consentimiento del usuario, nuestro sitio web utiliza cookies y tecnología de seguimiento similar 
	 para los fines que se detallan a continuación. Le pedimos que lea atentamente la siguiente información 
	 sobre cómo procesamos sus datos personales mediante el uso de cookies. Este Aviso de Cookies («Aviso de Cookies») 
	 regula el uso de cookies en https://www.ugtjjuanbs.com (el «Sitio Web»), operado por Sergio Guárdia i Jarauta,
	 como responsable del tratamiento, con domicilio social en Crta. de Barcelona 147, 1er, 4a 08290-Cerdanyola del Valles
	 Barcelona, España, con 
	 DNI 46645628H (en adelante, «FoodingEmotion» o «Nosotros»). A los efectos de este Aviso de Cookies, 
	 se entenderá por «Usuario» cualquier persona física que utilice el Sitio Web. Se informa al 
	 Usuario que las cookies de terceros utilizadas en el Sitio Web no son controladas por Pacha 
	 sino por el tercero correspondiente. Encontrará información detallada sobre los terceros que 
	 instalan cookies en el sitio web a continuación.
	 </p>

<p>Si su navegador está configurado para aceptar cookies, podemos recopilar información de identificación no personal de 
forma pasiva utilizando “cookies” y “etiquetas de página”. </p>


<h2>¿Qué es una cookie?</h2>
<p>Una cookie es un fichero que se descarga en su ordenador al acceder a determinadas páginas web. 
Las cookies permiten a una página web, entre otras cosas, almacenar y recuperar información sobre los 
hábitos de navegación de un usuario o de su equipo y, dependiendo de la información que contengan y de 
la forma en que utilice su equipo, pueden utilizarse para reconocer al usuario.</p>

<h4>Lea sobre el uso de cookies y cómo hacer que su sitio web sea compatible con S.S. UGT J-Juan Brake Systems San Cugat.</h4>
<h2>¿Qué es una etiqueta de página?</h2>
<p>Las “etiquetas de página”, también conocidas como balizas web o etiquetas gif, 
son una tecnología web que se utiliza para ayudar a rastrear la información de uso del correo electrónico o del 
sitio web, como cuántas veces se ha visto una página o un correo electrónico específico. 
Las etiquetas de página son invisibles para usted y cualquier parte de UGT Brake System, 
incluidos los anuncios o el correo electrónico enviado en nuestro nombre, puede contener etiquetas de página. </p>

<h2>¿UGT Brake System utiliza cookies? ¿Por qué?</h2>
<p>Si. Usamos cookies para personalizar su experiencia en el S.S UGT J.Juan Brake Systems San Cugat
(como generar contenido dinámicamente en páginas web diseñadas específicamente para usted), 
para ayudarlo a usar el Servicio de S.S. UGT J-Juan Brake Systems San Cugat (como ahorrar tiempo para que no le vuelva aparecer la ventana de aviso de cookies), 
para permitirnos monitorear estadísticamente cómo 
está utilizando el Servicio de S.S. UGT J-Juan Brake Systems San Cugat para que podamos mejorar nuestros articulos y para dirigir ciertos anuncios 
a su navegador que pueden ser de su interés o para determinar la popularidad de cierto contenido. 
Al usar cookies y etiquetas de página juntas, podemos mejorar el Contenido de S.S. UGT J-Juan Brake Systems San Cugaty medir la efectividad de nuestras 
campañas de publicidad y marketing.</p>

<p>Esta página web utiliza servicios de terceros para recopilar información con fines estadísticos y de uso de la web..</p>

<h2>¿Tengo que aceptarlos?</h2>
<p>No es necesario que acepte cookies para acceder al contenido de S.S. UGT J-Juan Brake Systems San Cugat Si rechaza las cookies, 
es posible que ciertas funciones o recursos de S.S. UGT J-Juan Brake Systems San Cugat no funcionen correctamente o no funcionen 
en absoluto y es posible que tenga una experiencia degradada.</p>

<p>Aunque la mayoría de los navegadores están configurados inicialmente para aceptar cookies, 
puede cambiar la configuración de su navegador para que le notifique cuando recibe una cookie o 
para rechazar las cookies en general. Tambien puede acceder a herramientas en opciones avanzadas y eliinar el historial 
activando la casilla de cookies Para obtener más información sobre cómo controlar la configuración de 
privacidad y la administración de cookies, haga clic en el enlace de su navegador a continuación.</p>

<ul class= "privacidad">

<li><a href="https://support.mozilla.org/es/kb/habilitar-y-deshabilitar-cookies-sitios-web-rastrear-preferencias?redirectslug=habilitar-y-deshabilitar-cookies-que-los-sitios-we&redirectlocale=es">
Firefox</a></li>


<li><a href="https://support.google.com/chrome/answer/95647?hl=es">
Chrome</a></li>




<li><a href="https://support.apple.com/es-es/HT201265">
Safari</a></li>

</ul>


<p>Para obtener más información sobre las cookies; cómo controlarlas, deshabilitarlas o eliminarlas, visite http://www.aboutcookies.org. Algunas redes de publicidad de terceros, como Google, le permiten optar por no participar o personalizar las preferencias asociadas con su navegación por Internet. Para obtener más información sobre cómo Google le permite personalizar estas preferencias, consulte su documentación.

<p>Todas las cookies, en nuestro sitio web y en cualquier otro lugar de la web, se dividen en una de cuatro categorías:</p>
<p><strong>Cookies estrictamente necesarias</strong> — estas cookies son esenciales para navegar por el sitio web y utilizar sus funciones, como acceder a áreas seguras del sitio. Las cookies que permiten que las tiendas web mantengan sus artículos en su carrito mientras compra en línea son un ejemplo de cookies estrictamente necesarias. Por lo general, estas cookies serán cookies de sesión de origen. Si bien no es necesario obtener el consentimiento para estas cookies, se debe explicar al usuario qué hacen y por qué son necesarias.</p>

<p><strong>Cookies de preferencias</strong> — también conocidas como “cookies de funcionalidad”, estas cookies permiten que un sitio web recuerde las elecciones que ha realizado en el pasado, como qué idioma prefiere, para qué región desea recibir informes meteorológicos o cuál es su nombre de usuario y contraseña. Puede iniciar sesión automáticamente.</p>

<p><strong>Cookies de estadísticas</strong> —también conocidas como “cookies de rendimiento”, estas cookies recopilan información sobre cómo utiliza un sitio web, como las páginas que visitó y los enlaces en los que hizo clic. Ninguna de esta información se puede utilizar para identificarlo. Todo es agregado y, por tanto, anónimo. Su único propósito es mejorar las funciones del sitio web. Esto incluye cookies de servicios de análisis de terceros siempre que las cookies sean para uso exclusivo del propietario del sitio web visitado.</p>

<p><strong>Cookies de marketing</strong> — estas cookies rastrean su actividad en línea para ayudar a los anunciantes a ofrecer publicidad más relevante o para limitar la cantidad de veces que ve un anuncio. Estas cookies pueden compartir esa información con otras organizaciones o anunciantes. Se trata de cookies persistentes y casi siempre de procedencia de terceros.</p>

<h2>Archivos de registro</h2>
<p>Recopilamos información no personal a través de nuestros archivos de registro de Internet, que registran datos como tipos de navegador, 
nombres de dominio y otros datos estadísticos anónimos relacionados con el uso del Servicio de S.S. UGT J-Juan Brake Systems San Cugat. Esta información puede usarse para 
analizar tendencias, administrar el Servicio de S.S. UGT J-Juan Brake Systems San Cugat, monitorear el uso del Servicio de S.S. UGT J-Juan Brake Systems San Cugat y recopilar información demográfica general. 
Podemos vincular esta información a información personal para estos y otros fines, como personalizar su experiencia en el Servicio de S.S. UGT J-Juan Brake Systems San Cugat y 
evaluar el Servicio de S.S. UGT J-Juan Brake Systems San Cugat en general.</p>

<h2>¿Qué es un almacenamiento local?</h2>
<p>El almacenamiento local es el componente del navegador que almacena localmente 
pares clave / valor con nombre dentro del navegador web de un cliente.</p>

<h2>Descripción de los cookies que utiliza nuestra web</h2>


<div class="descripcion">
<div class="d">
<h4>Nombre de la Cookie	</h4>
</div>
<div class="d">
<h4>Descripción de la Cookie</h4>
</div>
	<div class="d">
<h4>Categoría de la Cookie</h4>
</div>

</div>

<!------------------------------------->
<div class="descrip">
<div class="de">
<p>mindboxDeviceUUID</p>
</div>
<div class="de">
	<p>ID del usuario en Mindbox	</p>
</div>
	<div class="de">
<p>Estadísticas</p>
</div>

</div>
<!------------------------------------->
<div class="descrip">
<div class="de">
<p>directCrm-session</p>
</div>
<div class="de">
	<p>Sesión de la cookie de Mindbox</p>
</div>
	<div class="de">
<p>Estadísticas</p>
</div>

</div>

<!------------------------------------->
<div class="descrip">
<div class="de">
<p>popmechanic_sbjs_migrations	</p>

</div>
<div class="de">
<p>servicio de la cookie de Popmechanic</p>
</div>
	<div class="de">
<p>Estadísticas</p>
</div>

</div>

<!------------------------------------->
<div class="descrip">
<div class="de">
<p>_ga*</p>

</div>
<div class="de">
	<p>Cookie de Google Analytics</p>
</div>
	<div class="de">
<p>Estadísticas</p>
</div>

</div>

<!------------------------------------->
<div class="descrip">
<div class="de">

<p>_gid</p>

</div>
<div class="de">
	<p>ID del usuario de Google Analytics</p>

</div>
	<div class="de">
<p>Estadísticas</p>
</div>

</div>



<!------------------------------------->
<div class="descrip">
<div class="de">

<p>_gcl_au</p>

</div>
<div class="de">
	<p>Cookie de Google AdSense</p>
</div>
	<div class="de">
<p>Estadísticas</p>
</div>

</div>


<!------------------------------------->
<div class="descrip">
<div class="de">

<p>tmr_*</p>
</div>
<div class="de">

	<p>Cookies de MyTarget	</p>
</div>
	<div class="de">
<p>Estadísticas</p>
</div>

</div>

<!------------------------------------->
<div class="descrip">
<div class="de">
<p>_ym_*</p>
</div>
<div class="de">
<p>Cookies de Yandex.Metrica</p>
</div>
	<div class="de">
<p>Estadísticas</p>
</div>

</div>

<!------------------------------------->
<div class="descrip">
<div class="de">

<p>_fbp</p>
</div>
<div class="de">
<p>	Cookie de Facebook Pixel</p>
</div>
	<div class="de">
<p>Estadísticas</p>
</div>

</div>


















</div>

    {% endblock cookie %}


</div>
{% endblock content %}
<!---DIV DEL ARTICULO----------------->

</div>


<!--FIN DIV DEL MAIN------->
	 

descargas/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block titulo %}Ugt Valles{% endblock titulo %}




    <!--------------------------------------------------------------------->
      <!--------------------------------------------------------------------->
      <div class="main">
          <!---------GRID COLUM 1/2-->
        <div class="main-primero"> 1</div>

        {% block content %}
          <!---GRID 2/10.COLUMN.........-->
          <div class="articulo"> 
            <div class="primer-segmento">

        <!-------REUNIONES -->
        <div class ="reuniones">
   
        <div class="descarga-reuniones">
          <h1> <a href="{% url 'descargas:reuniones' %}">
            {% trans 'Resumén de Reuniones del Comité' %}</a>
          </h1>

            <div class="reunion-image">
              <img src="{% static 'img/iconos/reunion.png' %}" alt="Image" class="">
           </div>
            
        </div>

            
          
      </div>
      <!------FIN REUNIONES--------->

      <!-----CALENDARIOS------------>
      <div class ="calendarios">

           <div class="descarga-calendarios">
             <h1> <a href="{% url 'descargas:calendario' %}"> {% trans 'Calendarios' %}</a></h1>
   
             <div class="calendario-image">
             <img src="{% static 'img/iconos/calendario.gif' %}" alt="Image" class="cover-img">
            </div>

          </div>
                       
      </div>
      <!---FIN CALENDARIO---------------------------->
    </div>
    <!---------------------FIN PRIMER SEGMENTO ROW-------------->

            
 <!-------SEGUNDO SEGMENTO----ROW--------->
  <div class="segundo-segmento">
    <!------------------------------->
    <div class="permisos">
    
        <div class="descarga-permisos"> 
          <h1> <a href="{% url 'descargas:permisos' %}">
          {% trans 'Permisos Retribuidos' %}</a>
          </h1>
     
          <div class="permiso-image">
          <img src="{% static 'img/iconos/permiso.png' %}" alt="Image" class="">
          </div>
        </div>

         
      </div>
      <!----------------------------------->
      <!----------------------------------->
      <div class ="prevencion">

        <div class="descarga-permisos"> 
       
            <h1> <a href="{% url 'descargas:prevencion' %}"> 
            {% trans 'Seguridad y Salud ' %}

            {% trans 'Prevención y Medio Ambiente ' %}
            </a>
            </h1>

            <div class="prevencion-image">
            <img src="{% static 'img/iconos/seguridad.png' %}" alt="Image" class="cover-img">
            </div>
         
          </div>
          </div>
        <!---------------------------------->
    </div>
    <!------FIN SEGUNDO SEGMENTO ROW-------------------------->

    <!---TERCER SEGMENTO UNICO BLOQUE--CONVENIO PROVINCIAL------------------------>
    <div class="tercer-segmento">
      <div class="descarga-convenio">
    
     
        <div class="convenio-image">
          <img src="{% static 'img/iconos/meca.png' %}" alt="Image" class="">
          </div>
       
          <div class="convenio-titulo">
          <h1><a href="{% url 'descargas:convenio' %}"> 
            {% trans 'Convenio Provincial Barcelona' %}
            </a>
          </h1>
      
        </div>
   

      </div>
    </div>
    <!--------------------------------------------------------->
            

    <div class= "cuarto-segmento">
    <h1>{% trans ' Afiliate a UGT' %}</h1>
    <h2>{% trans 'Qué ventajas supone afiliarse a UGT?' %} </h2>
        <div class="primer-cuarto">
        <h1>{% trans 'INFORMACIÓN Y ASESORAMIENTO PERMANENTE' %}</h1>

        <p> {% blocktrans trimmed %}
         'Contratación, salarios, vacaciones, prevención de riesgos laborales, nóminas, jornadas, convenios colectivos, 
          liquidaciones, finiquitos, jubilaciones, pensiones, Seguridad Social, expedientes de regulación, despidos, etc..'
          {% endblocktrans %}
        </p>
        </div>
        <!---------------R-->
          <div class="row">
          <!-----------------1--->
          <div class="row1">
          <h1>{% trans 'GABINETES JURÍDICOS ESPECIALIZADOS' %}</h1>
          <p>{% trans 'Abogados/as laboralistas, etc..' %}</p>
          </div>
          <!-------------------1--->
          <!-------------------2-->
              <div class="row2">
              <h1>{% trans '¡¡AFILIATE!!' %}</h1>
              </div>
              <!----------------2-->
               </div>
               <!--------------R--->
              
              <!------------------->
              <div class="encolumn">
               <h1>{% trans 'FORMACIÓN CONTÍNUA' %}</h1>
               <p>
                {% blocktrans trimmed %}
             Adaptada a los puestos de trabajo, sindical específica a los delegados/as de personal, 
                miembros de comités y delegados/as de Salud Laboral.
                {% endblocktrans %}
               </p>
               </div>
               <!------------------>

               </div>

            
        </div>

        {% endblock content %}

        </div>

 


       
             

descargas/templates/traduccion.html
{% get_current_language as LANGUAGE_CODE %}
<H1>{{LANGUAGE_CODE}}</H1>
<form action="{% url 'set_language' %}" method="POST">
  {% csrf_token %}
  <input type="hidden" name="next" value="{{redirect_to}}">
  <select name="language" id="">
    {% get_available_languages as LANGUAGES %}
    {% get_language_info_list for LANGUAGES as Languages %}
    {% for Language in Languages %}
    <option value="{{language.code}}" {% if language.code == LANGUAGE_CODE %} selected {% endif %}>
      {{Language.name_Local}} {{Language.code}}
    </option>
    {% endfor %}
  </select>
  <input type="submit" value="Go">
</form>

<!------------------------------------------------------------>

{% get_language_info_list for LANGUAGES as languages %}
{% if LANGUAGE_CODE == languages.0.code %}
    <form action="{% url 'set_language' %}" method="post">
    {% csrf_token %}
    <div class="lang-btn">
        <input name="next" type="hidden" value="{{ redirect_to }}" />
        <input name="language" type="hidden" value="{{ languages.1.code }}" />
        <button type="submit"><img width="30" src="{% static 'united-kingdom.png' %}" alt=""></button>
        </div>
        </form>
{% else %}
    <form action="{% url 'set_language' %}" method="post">
    {% csrf_token %}
        <div class="lang-btn">
            <input name="next" type="hidden" value="{{ redirect_to }}" />
            <input name="language" type="hidden" value="{{ languages.0.code }}" />
            <button type="submit"><img width="30" src="{% static 'turkey.png' %}" alt=""></button>
        </div>
    </form>
{% endif %}



<!-------------------------------------------------->
{% load i18n %} {#1#}
<form action="{% url 'set_language' %}" method="post">  {#2#}
    {% csrf_token %}  {#3#}
    <select name="language">  {#4#}
        {% get_current_language as LANGUAGE_CODE %}  {#5#}
        {% get_available_languages as LANGUAGES %}  {#6#}
        {% get_language_info_list for LANGUAGES as languages %}  {#7#}
        {% for language in languages %}
            <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>  {#8#}
                {{ language.name_local }} ({{ language.code }})
            </option>
        {% endfor %}
    </select>
    <input type="submit" value="Switch">  {#9#}
</form>
{% translate "I am localized inside the template." %}  {#10#}


<!---------------------------------------------------->

{% load cms_tags i18n %}
{% for language in languages %}
<a href="{% page_language_url language.0 %}"{% ifequal lang language.0 %} class="current"{% endifequal %}>
<img src="{{ MEDIA_URL }}[path to your flags images]{{ language.0 }}.gif" /></a>
{% endfor %}


<!---------------------------------------------->